// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dhawalhost/go-service-template/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Service
func (_mock *Service) Create(ctx context.Context, tenantID string, req service.CreateRequest) (*service.Example, error) {
	ret := _mock.Called(ctx, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *service.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.CreateRequest) (*service.Example, error)); ok {
		return returnFunc(ctx, tenantID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.CreateRequest) *service.Example); ok {
		r0 = returnFunc(ctx, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, service.CreateRequest) error); ok {
		r1 = returnFunc(ctx, tenantID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - req service.CreateRequest
func (_e *Service_Expecter) Create(ctx interface{}, tenantID interface{}, req interface{}) *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create", ctx, tenantID, req)}
}

func (_c *Service_Create_Call) Run(run func(ctx context.Context, tenantID string, req service.CreateRequest)) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 service.CreateRequest
		if args[2] != nil {
			arg2 = args[2].(service.CreateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Create_Call) Return(example *service.Example, err error) *Service_Create_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func(ctx context.Context, tenantID string, req service.CreateRequest) (*service.Example, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Service
func (_mock *Service) Delete(ctx context.Context, tenantID string, id string) error {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Service_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *Service_Expecter) Delete(ctx interface{}, tenantID interface{}, id interface{}) *Service_Delete_Call {
	return &Service_Delete_Call{Call: _e.mock.On("Delete", ctx, tenantID, id)}
}

func (_c *Service_Delete_Call) Run(run func(ctx context.Context, tenantID string, id string)) *Service_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Delete_Call) Return(err error) *Service_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Delete_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) error) *Service_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Service
func (_mock *Service) Get(ctx context.Context, tenantID string, id string) (*service.Example, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *service.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*service.Example, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *service.Example); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Service_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *Service_Expecter) Get(ctx interface{}, tenantID interface{}, id interface{}) *Service_Get_Call {
	return &Service_Get_Call{Call: _e.mock.On("Get", ctx, tenantID, id)}
}

func (_c *Service_Get_Call) Run(run func(ctx context.Context, tenantID string, id string)) *Service_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Get_Call) Return(example *service.Example, err error) *Service_Get_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Service_Get_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*service.Example, error)) *Service_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Service
func (_mock *Service) List(ctx context.Context, tenantID string, params service.ListParams) ([]service.Example, int64, error) {
	ret := _mock.Called(ctx, tenantID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Example
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.ListParams) ([]service.Example, int64, error)); ok {
		return returnFunc(ctx, tenantID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.ListParams) []service.Example); ok {
		r0 = returnFunc(ctx, tenantID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, service.ListParams) int64); ok {
		r1 = returnFunc(ctx, tenantID, params)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, service.ListParams) error); ok {
		r2 = returnFunc(ctx, tenantID, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Service_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Service_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - params service.ListParams
func (_e *Service_Expecter) List(ctx interface{}, tenantID interface{}, params interface{}) *Service_List_Call {
	return &Service_List_Call{Call: _e.mock.On("List", ctx, tenantID, params)}
}

func (_c *Service_List_Call) Run(run func(ctx context.Context, tenantID string, params service.ListParams)) *Service_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 service.ListParams
		if args[2] != nil {
			arg2 = args[2].(service.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_List_Call) Return(examples []service.Example, n int64, err error) *Service_List_Call {
	_c.Call.Return(examples, n, err)
	return _c
}

func (_c *Service_List_Call) RunAndReturn(run func(ctx context.Context, tenantID string, params service.ListParams) ([]service.Example, int64, error)) *Service_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Service
func (_mock *Service) Update(ctx context.Context, tenantID string, id string, req service.UpdateRequest) (*service.Example, error) {
	ret := _mock.Called(ctx, tenantID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *service.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, service.UpdateRequest) (*service.Example, error)); ok {
		return returnFunc(ctx, tenantID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, service.UpdateRequest) *service.Example); ok {
		r0 = returnFunc(ctx, tenantID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, service.UpdateRequest) error); ok {
		r1 = returnFunc(ctx, tenantID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Service_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
//   - req service.UpdateRequest
func (_e *Service_Expecter) Update(ctx interface{}, tenantID interface{}, id interface{}, req interface{}) *Service_Update_Call {
	return &Service_Update_Call{Call: _e.mock.On("Update", ctx, tenantID, id, req)}
}

func (_c *Service_Update_Call) Run(run func(ctx context.Context, tenantID string, id string, req service.UpdateRequest)) *Service_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 service.UpdateRequest
		if args[3] != nil {
			arg3 = args[3].(service.UpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_Update_Call) Return(example *service.Example, err error) *Service_Update_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Service_Update_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string, req service.UpdateRequest) (*service.Example, error)) *Service_Update_Call {
	_c.Call.Return(run)
	return _c
}
