// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dhawalhost/go-service-template/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Repository
func (_mock *Repository) Create(ctx context.Context, example *repository.Example) error {
	ret := _mock.Called(ctx, example)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.Example) error); ok {
		r0 = returnFunc(ctx, example)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - example *repository.Example
func (_e *Repository_Expecter) Create(ctx interface{}, example interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, example)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, example *repository.Example)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.Example
		if args[1] != nil {
			arg1 = args[1].(*repository.Example)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Create_Call) Return(err error) *Repository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(ctx context.Context, example *repository.Example) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Repository
func (_mock *Repository) Delete(ctx context.Context, tenantID string, id string) error {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *Repository_Expecter) Delete(ctx interface{}, tenantID interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, tenantID, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, tenantID string, id string)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(err error) *Repository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type Repository
func (_mock *Repository) GetByID(ctx context.Context, tenantID string, id string) (*repository.Example, error) {
	ret := _mock.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *repository.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.Example, error)); ok {
		return returnFunc(ctx, tenantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.Example); ok {
		r0 = returnFunc(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
func (_e *Repository_Expecter) GetByID(ctx interface{}, tenantID interface{}, id interface{}) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tenantID, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, tenantID string, id string)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(example *repository.Example, err error) *Repository_GetByID_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string) (*repository.Example, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(ctx context.Context, tenantID string, params repository.ListParams) ([]repository.Example, int64, error) {
	ret := _mock.Called(ctx, tenantID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.Example
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.ListParams) ([]repository.Example, int64, error)); ok {
		return returnFunc(ctx, tenantID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.ListParams) []repository.Example); ok {
		r0 = returnFunc(ctx, tenantID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.ListParams) int64); ok {
		r1 = returnFunc(ctx, tenantID, params)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, repository.ListParams) error); ok {
		r2 = returnFunc(ctx, tenantID, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - params repository.ListParams
func (_e *Repository_Expecter) List(ctx interface{}, tenantID interface{}, params interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, tenantID, params)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, tenantID string, params repository.ListParams)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.ListParams
		if args[2] != nil {
			arg2 = args[2].(repository.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(examples []repository.Example, n int64, err error) *Repository_List_Call {
	_c.Call.Return(examples, n, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(ctx context.Context, tenantID string, params repository.ListParams) ([]repository.Example, int64, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository) Update(ctx context.Context, example *repository.Example) error {
	ret := _mock.Called(ctx, example)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.Example) error); ok {
		r0 = returnFunc(ctx, example)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - example *repository.Example
func (_e *Repository_Expecter) Update(ctx interface{}, example interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, example)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, example *repository.Example)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.Example
		if args[1] != nil {
			arg1 = args[1].(*repository.Example)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Update_Call) Return(err error) *Repository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(ctx context.Context, example *repository.Example) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}
